# https://terramate.io/docs/cli/automation/github-actions/drift-check-workflow
name: Drift Detection - On Demand

on:
  workflow_dispatch:

jobs:
  drift-detection:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: read
      checks: read

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Infrastructure Tools
        uses: ./.github/actions/setup-infra-tools
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: us-east-1

      - name: Authenticate with AWS
        uses: ./.github/actions/setup-aws
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: us-east-1

      - name: Initialize Terragrunt
        id: init
        run: |
          terramate run \
           --parallel 1 \
           -- \
           terragrunt init --terragrunt-non-interactive -lock-timeout=5m

      # To avoid error due to uncommitted files from previous steps
      - name: Check for uncommitted files
        run: |
          git add .
          git diff --cached --exit-code || echo "Found uncommitted files, but continuing..."

      - name: Run drift detection
        id: drift
        run: |
          terramate run \
            --parallel 5 \
            --sync-drift-status \
            --continue-on-error \
            --terraform-plan-file=drift.tfplan \
            --terragrunt \
            -- \
            terragrunt plan -out drift.tfplan -detailed-exitcode -lock=false

      # # Optional step to reconcile (apply) the drifted stacks
      # # This only applies to stack with a `reconcile` tag by default
      # # Uncomment if desired
      # - name: Check for auto reconcile
      #   id: find-drifted
      #   run: |
      #     terramate list \
      #       --status=drifted \
      #       --tags reconcile
      #
      # - name: Drift reconciliation
      #   id: drift-reconcile
      #   if: steps.find-drifted.outputs.stdout
      #   run: |
      #     terramate run \
      #       --status=drifted \
      #       --tags reconcile \
      #       --parallel 5 \
      #       --sync-deployment \
      #       --terraform-plan-file=drift.tfplan \
      #       --terragrunt \
      #       -- \
      #       terragrunt apply -input=false -auto-approve -lock-timeout=5m drift.tfplan
